### PR TITLE
added removeChild to trash can

### PR DESCRIPTION
**Pull request by thenorthstarblues**
addresses #86

### CODE REVIEW

**Review by siteations — COMMENTED** [review]
looks good. just building/running for a test drive.

**Review by siteations — COMMENTED** [review]
This seems fine in the children direction. Any desire to add the same for parents? If you throw out a 'div' but leave its' kids, should their parent reference change (yes, but do we really care)?

**Comment by thenorthstarblues** [comment]
Doesn't really matter at this point because one of the rules right now is that you can't move boxes that have other boxes inside of them

**Comment by siteations** [comment]
sure. sounds reasonable. I'm merging it.

**Pull request merged**
